### PR TITLE
Shadow DOM v1 compatibility.

### PR DESCRIPTION
**Pull request by PatrykSzwer**
According to Starcounter/RebelsLounge#76

### CODE REVIEW

**Comment by tomalec** [comment]
Please consider comments from https://github.com/Juicy/juicy-draggable/pull/2

**Review by tomalec — CHANGES_REQUESTED** [review]
Please consider comments from https://github.com/Juicy/juicy-draggable/pull/2

**Comment by warpech** [comment]
Ping @PatrykSzwer

**Comment by PatrykSzwer** [comment]
After discussion with @tomalec, We're closing this PR for now, since this element is deprecated. If It will become needed then we will reopen this. For now, closing.

**Pull request closed without merging**
